// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using trial_project_for_MVC_Core.EntityDB;

#nullable disable

namespace trial_project_for_MVC_Core.Migrations
{
    [DbContext(typeof(UniversityEntity))]
    partial class UniversityEntityModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DepartmentTeacherDTO", b =>
                {
                    b.Property<int>("DepartmentsId")
                        .HasColumnType("int");

                    b.Property<int>("teachersId")
                        .HasColumnType("int");

                    b.HasKey("DepartmentsId", "teachersId");

                    b.HasIndex("teachersId");

                    b.ToTable("DepartmentTeacherDTO");
                });

            modelBuilder.Entity("LabTeacherDTO", b =>
                {
                    b.Property<int>("LabsId")
                        .HasColumnType("int");

                    b.Property<int>("TeachersId")
                        .HasColumnType("int");

                    b.HasKey("LabsId", "TeachersId");

                    b.HasIndex("TeachersId");

                    b.ToTable("LabTeacherDTO");
                });

            modelBuilder.Entity("trial_project_for_MVC_Core.Models.College", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UniversityId1")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UniversityId1");

                    b.ToTable("Colleges");
                });

            modelBuilder.Entity("trial_project_for_MVC_Core.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CollegeId")
                        .HasColumnType("int");

                    b.Property<int?>("LabId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CollegeId");

                    b.HasIndex("LabId");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("trial_project_for_MVC_Core.Models.Lab", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Lab");
                });

            modelBuilder.Entity("trial_project_for_MVC_Core.Models.StudentDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LabId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("LabId");

                    b.ToTable("StudentDTO");
                });

            modelBuilder.Entity("trial_project_for_MVC_Core.Models.TeacherDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TeacherDTO");
                });

            modelBuilder.Entity("trial_project_for_MVC_Core.Models.University", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Universities");
                });

            modelBuilder.Entity("DepartmentTeacherDTO", b =>
                {
                    b.HasOne("trial_project_for_MVC_Core.Models.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("trial_project_for_MVC_Core.Models.TeacherDTO", null)
                        .WithMany()
                        .HasForeignKey("teachersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LabTeacherDTO", b =>
                {
                    b.HasOne("trial_project_for_MVC_Core.Models.Lab", null)
                        .WithMany()
                        .HasForeignKey("LabsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("trial_project_for_MVC_Core.Models.TeacherDTO", null)
                        .WithMany()
                        .HasForeignKey("TeachersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("trial_project_for_MVC_Core.Models.College", b =>
                {
                    b.HasOne("trial_project_for_MVC_Core.Models.University", "University")
                        .WithMany("colleges")
                        .HasForeignKey("UniversityId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("University");
                });

            modelBuilder.Entity("trial_project_for_MVC_Core.Models.Department", b =>
                {
                    b.HasOne("trial_project_for_MVC_Core.Models.College", "College")
                        .WithMany("Departments")
                        .HasForeignKey("CollegeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("trial_project_for_MVC_Core.Models.Lab", null)
                        .WithMany("Departments")
                        .HasForeignKey("LabId");

                    b.Navigation("College");
                });

            modelBuilder.Entity("trial_project_for_MVC_Core.Models.StudentDTO", b =>
                {
                    b.HasOne("trial_project_for_MVC_Core.Models.Department", null)
                        .WithMany("students")
                        .HasForeignKey("DepartmentId");

                    b.HasOne("trial_project_for_MVC_Core.Models.Lab", null)
                        .WithMany("Students")
                        .HasForeignKey("LabId");
                });

            modelBuilder.Entity("trial_project_for_MVC_Core.Models.College", b =>
                {
                    b.Navigation("Departments");
                });

            modelBuilder.Entity("trial_project_for_MVC_Core.Models.Department", b =>
                {
                    b.Navigation("students");
                });

            modelBuilder.Entity("trial_project_for_MVC_Core.Models.Lab", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("trial_project_for_MVC_Core.Models.University", b =>
                {
                    b.Navigation("colleges");
                });
#pragma warning restore 612, 618
        }
    }
}
